name: termui_monorepo
description: Root workspace of the termui monorepo.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.11.0 <4.0.0"

workspace:
  - packages/termui
  - packages/termui_flutter
  - packages/termui_flutter/example
  - packages/termui_shared_examples
  - packages/termui_recorder
  - packages/termui_test
  - packages/termui_hotreload
  - packages/termui_hotreload/example
  - packages/pty2
  - packages/termui_pty
  - packages/termui_audio

dev_dependencies:
  melos: ^8.1.0

melos:
  command:
    bootstrap:
      environment:
        sdk: ">=3.11.0 <4.0.0"
        flutter: ">=3.0.0"
  scripts:
    analyze:
      run: dart run melos exec -c 1 -- "dart analyze"
      description: Run static analysis on all packages.

    test:dart:
      description: Run unit tests for pure Dart packages.
      exec:
        command: dart test --reporter=expanded
        failFast: true
      packageFilters:
        dirExists: test
        flutter: false

    test:flutter:
      description: Run unit tests for Flutter packages.
      exec:
        command: flutter test --reporter=expanded
        failFast: true
      packageFilters:
        dirExists: test
        flutter: true

    test:all:
      steps:
        - melos run test:dart
        - melos run test:flutter
      packageFilters:
        dirExists: test
      description: Run all tests in the monorepo.
dependencies:
  archive: ^4.0.9
