include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - always_use_package_imports
    - avoid_print
    - public_member_api_docs

analyzer:
  exclude:
    - "**/*.g.dart"
