name: termui_hotreload
description: An optional companion package for termui that provides dead-simple automatic hot reloading during development.
version: 0.6.18
repository: https://github.com/jtmcdole/termui/tree/main/packages/termui_hotreload

environment:
  sdk: ">=3.11.0 <4.0.0"

topics:
  - cli
  - tui
  - terminal
  - development
  - hotreload

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

resolution: workspace

dependencies:
  termui: ^0.9.1
  hotreloader: ^4.2.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
