name: examples
description: Examples for termui.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  termui:
    path: ../packages/termui
  characters: ^1.4.0
