name: termui_pty
description: A custom ANSI terminal emulator and PTY view for termui.
version: 0.3.5
repository: https://github.com/jtmcdole/termui/tree/main/packages/termui_pty

resolution: workspace

topics:
  - cli
  - tui
  - terminal
  - console
  - pty

platforms:
  windows:
  macos:
  linux:

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  termui: ^0.7.5
  pty2: ^0.5.1
  characters: ^1.4.0

dev_dependencies:
  test: ">=1.24.0 <2.0.0"
  termui_test: ^0.2.6+9
  termui_shared_examples:
    path: ../termui_shared_examples
  benchmark_harness: ^2.2.0
