import 'dart:async';
import 'package:flutter_soloud/flutter_soloud.dart' as sol;
import '../../api/audio_engine.dart';
import '../../api/audio_types.dart';

/// An audio buffer loaded into the Flutter backend.
class FlutterAudioBuffer implements AudioBuffer {
  final sol.AudioSource _source;
  final Map<int, Completer<void>> _activeVoices = {};
  late final StreamSubscription<sol.StreamSoundEvent> _sub;

  /// Creates a new Flutter audio buffer.
  FlutterAudioBuffer(this._source) {
    _sub = _source.soundEvents.listen((event) {
      if (event.event == sol.SoundEventType.handleIsNoMoreValid) {
        final completer = _activeVoices.remove(event.handle.id);
        if (completer != null && !completer.isCompleted) {
          completer.complete();
        }
      }
    });
  }

  /// Registers a newly played voice and its completion future.
  void registerVoice(int voiceId, Completer<void> completer) {
    _activeVoices[voiceId] = completer;
  }

  /// Cancels all active voice completers and disposes the buffer.
  void dispose() {
    _sub.cancel();
    for (final c in _activeVoices.values) {
      if (!c.isCompleted) c.complete();
    }
    _activeVoices.clear();
  }

  /// The unique hash identifier generated by the SoLoud backend.
  @override
  int get hash => _source.soundHash.hash;
}

/// A mixing bus for grouping audio voices in the Flutter backend.
class FlutterAudioBus implements AudioBus {
  final sol.Bus _bus;

  /// Creates a new Flutter audio bus.
  const FlutterAudioBus(this._bus);

  /// The unique ID of the bus.
  @override
  int get id => _bus.busId;

  /// Sets the volume for this bus.
  @override
  void setVolume(double volume) {
    sol.SoLoud.instance.setVolume(sol.SoundHandle(_bus.busId), volume);
  }
}

/// The Flutter implementation of [TermuiAudioEngine].
class FlutterAudioEngine implements TermuiAudioEngine {
  final sol.SoLoud _engine = sol.SoLoud.instance;

  @override
  Duration getBufferDuration(AudioBuffer buffer) {
    final flutterBuffer = buffer as FlutterAudioBuffer;
    return _engine.getLength(flutterBuffer._source);
  }

  @override
  Duration getVoicePosition(AudioVoice voice) {
    return _engine.getPosition(sol.SoundHandle(voice.id));
  }

  @override
  void seek(AudioVoice voice, Duration position) {
    _engine.seek(sol.SoundHandle(voice.id), position);
  }

  @override
  Future<void> init() async {
    if (!_engine.isInitialized) {
      await _engine.init();
    }
  }

  @override
  Future<void> dispose() async {
    if (_engine.isInitialized) {
      _engine.deinit();
    }
  }

  @override
  Future<AudioBuffer> loadFile(
    String path, {
    LoadProgressCallback? onProgress,
  }) async {
    onProgress?.call(0.1);
    final source = await _engine.loadFile(path);
    onProgress?.call(1.0);
    return FlutterAudioBuffer(source);
  }

  @override
  Future<AudioBuffer> loadUrl(
    String url, {
    LoadProgressCallback? onProgress,
  }) async {
    onProgress?.call(0.1);
    final source = await _engine.loadUrl(url);
    onProgress?.call(1.0);
    return FlutterAudioBuffer(source);
  }

  @override
  Future<AudioBuffer> loadWaveform(WaveForm shape, double frequency) async {
    final solShape = sol.WaveForm.values.firstWhere(
      (e) => e.name == shape.name,
    );
    final source = await _engine.loadWaveform(solShape, true, 1.0, frequency);
    return FlutterAudioBuffer(source);
  }

  @override
  AudioVoice play(AudioBuffer buffer, {bool loop = false, AudioBus? bus}) {
    final flutterBuffer = buffer as FlutterAudioBuffer;
    final busId = bus?.id ?? 0;
    final voice = _engine.play(
      flutterBuffer._source,
      looping: loop,
      busId: busId,
    );
    final completer = Completer<void>();
    flutterBuffer.registerVoice(voice.id, completer);
    return AudioVoice(voice.id, completer.future);
  }

  @override
  void stop(AudioVoice voice) {
    sol.SoLoud.instance.stop(sol.SoundHandle(voice.id));
  }

  @override
  void setVoiceVolume(AudioVoice voice, double volume) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    sol.SoLoud.instance.setVolume(sol.SoundHandle(voice.id), volume);
  }

  @override
  AudioVoice play3d(AudioBuffer buffer, double x, double y, double z) {
    final flutterBuffer = buffer as FlutterAudioBuffer;
    final voice = _engine.play3d(flutterBuffer._source, x, y, z);
    final completer = Completer<void>();
    flutterBuffer.registerVoice(voice.id, completer);
    return AudioVoice(voice.id, completer.future);
  }

  @override
  void set3dSourceParameters(
    AudioVoice voice,
    double x,
    double y,
    double z, {
    double vx = 0.0,
    double vy = 0.0,
    double vz = 0.0,
  }) {
    _engine.set3dSourceParameters(
      sol.SoundHandle(voice.id),
      x,
      y,
      z,
      vx,
      vy,
      vz,
    );
  }

  @override
  void set3dSourceMinMaxDistance(
    AudioVoice voice,
    double minDistance,
    double maxDistance,
  ) {
    _engine.set3dSourceMinMaxDistance(
      sol.SoundHandle(voice.id),
      minDistance,
      maxDistance,
    );
  }

  @override
  void set3dSourceAttenuation(
    AudioVoice voice,
    AttenuationModel attenuationModel,
    double attenuationRolloffFactor,
  ) {
    _engine.set3dSourceAttenuation(
      sol.SoundHandle(voice.id),
      attenuationModel.index,
      attenuationRolloffFactor,
    );
  }

  @override
  void setRelativePlaySpeed(AudioVoice voice, double speed) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    _engine.setRelativePlaySpeed(sol.SoundHandle(voice.id), speed);
  }

  @override
  void fadeRelativePlaySpeed(
    AudioVoice voice,
    double speed,
    Duration duration,
  ) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    _engine.fadeRelativePlaySpeed(sol.SoundHandle(voice.id), speed, duration);
  }

  @override
  void fadeVolume(AudioVoice voice, double targetVolume, Duration duration) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    _engine.fadeVolume(sol.SoundHandle(voice.id), targetVolume, duration);
  }

  @override
  int createFilter(FilterType type) {
    return type.index;
  }

  @override
  void attachFilterToBus(AudioBus bus, int filterId) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solFilter = sol.FilterType.values[filterId];
    // ignore: invalid_use_of_internal_member
    solFilter.activate(null, bus.id);
  }

  @override
  void setFilterParameter(
    AudioBus bus,
    int filterId,
    int paramId,
    double value,
  ) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solFilter = sol.FilterType.values[filterId];
    // ignore: invalid_use_of_internal_member
    solFilter.fadeFilterParameter(null, bus.id, paramId, value, Duration.zero);
  }

  @override
  void fadeFilterParameter(
    AudioBus bus,
    int filterId,
    int paramId,
    double targetValue,
    Duration duration,
  ) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solFilter = sol.FilterType.values[filterId];
    // ignore: invalid_use_of_internal_member
    solFilter.fadeFilterParameter(null, bus.id, paramId, targetValue, duration);
  }

  @override
  AudioVoice playSprite(
    AudioBuffer buffer, {
    required Duration start,
    required Duration duration,
  }) {
    final voice = play(buffer);
    seek(voice, start);
    Timer(duration, () {
      try {
        stop(voice);
      } catch (_) {}
    });
    return voice;
  }

  @override
  AudioBus createBus() {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solBus = sol.Bus();
    solBus.playOnEngine();
    return FlutterAudioBus(solBus);
  }

  @override
  void destroyBus(AudioBus bus) {
    if (!_engine.isInitialized) return;
    final flutterBus = bus as FlutterAudioBus;
    flutterBus._bus.dispose();
  }
}
