import 'dart:async';
import 'dart:math' as math;
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:flutter_soloud/flutter_soloud.dart' as sol;
// ignore: implementation_imports
import 'package:flutter_soloud/src/bindings/soloud_controller.dart'
    as soloud_controller;
import '../../api/audio_engine.dart';
import '../../api/audio_types.dart';

/// An audio buffer loaded into the Flutter backend.
final class FlutterAudioBuffer implements AudioBuffer {
  final sol.AudioSource _source;
  late final StreamSubscription<sol.StreamSoundEvent> _sub;

  /// Creates a new Flutter audio buffer.
  FlutterAudioBuffer(this._source, FlutterAudioEngine engine) {
    _sub = _source.soundEvents.listen((event) {
      if (event.event == sol.SoundEventType.handleIsNoMoreValid) {
        engine._completeVoice(event.handle.id);
      }
    });
  }

  /// The underlying SoLoud audio source.
  sol.AudioSource get source => _source;

  /// Disposes of the internal sound event listener subscription.
  void dispose() {
    _sub.cancel();
  }

  /// The unique hash identifier generated by the SoLoud backend.
  @override
  int get hash => _source.soundHash.hash;
}

/// A mixing bus for grouping audio voices in the Flutter backend.
final class FlutterAudioBus implements AudioBus {
  final sol.Bus _bus;

  /// Creates a new Flutter audio bus.
  const FlutterAudioBus(this._bus);

  /// The unique ID of the bus.
  @override
  int get id => _bus.busId;

  /// Sets the volume for this bus.
  @override
  void setVolume(double volume) {
    sol.SoLoud.instance.setVolume(sol.SoundHandle(_bus.busId), volume);
  }
}

/// The Flutter implementation of [TermuiAudioEngine].
final class FlutterAudioEngine implements TermuiAudioEngine {
  final sol.SoLoud _engine = sol.SoLoud.instance;
  // TODO: Track potential memory leaks here if voiceEnded callbacks are missed (e.g. loops).
  final Map<int, Completer<void>> _activeVoices = {};
  sol.AudioData? _audioData;

  @override
  Duration getBufferDuration(AudioBuffer buffer) {
    if (buffer case FlutterAudioBuffer(:final source)) {
      return _engine.getLength(source);
    }
    return Duration.zero;
  }

  @override
  Duration getVoicePosition(AudioVoice voice) {
    return _engine.getPosition(sol.SoundHandle(voice.id));
  }

  @override
  void seek(AudioVoice voice, Duration position) {
    _engine.seek(sol.SoundHandle(voice.id), position);
  }

  @override
  Future<void> init({bool enableVisualization = true}) async {
    if (!_engine.isInitialized) {
      await _engine.init();
      _engine.setVisualizationEnabled(enableVisualization);
      _audioData = sol.AudioData(sol.GetSamplesKind.wave);
    }
  }

  void _completeVoice(int voiceId) {
    final completer = _activeVoices.remove(voiceId);
    if (completer != null && !completer.isCompleted) {
      completer.complete();
    }
  }

  @override
  Future<void> dispose() async {
    for (final c in _activeVoices.values) {
      if (!c.isCompleted) c.complete();
    }
    _activeVoices.clear();
    _audioData?.dispose();
    _audioData = null;
    if (_engine.isInitialized) {
      _engine.deinit();
    }
  }

  @override
  Future<AudioBuffer> loadFile(
    String path, {
    LoadProgressCallback? onProgress,
  }) async {
    onProgress?.call(0.1);
    final source = await _engine.loadFile(path);
    onProgress?.call(1.0);
    return FlutterAudioBuffer(source, this);
  }

  @override
  Future<AudioBuffer> loadUrl(
    String url, {
    LoadProgressCallback? onProgress,
  }) async {
    onProgress?.call(0.1);
    final source = await _engine.loadUrl(url);
    onProgress?.call(1.0);
    return FlutterAudioBuffer(source, this);
  }

  @override
  Future<Uint8List> loadFileBytes(String path) async {
    final byteData = await rootBundle.load(path);
    return Uint8List.sublistView(byteData);
  }

  @override
  Future<void> disposeBuffer(AudioBuffer buffer) async {
    if (buffer case FlutterAudioBuffer b) {
      b.dispose();
      await _engine.disposeSource(b.source);
    }
  }

  Uint8List _generateWaveformPcmWav({
    required WaveForm shape,
    required double frequency,
    Duration duration = const Duration(milliseconds: 250),
    int sampleRate = 44100,
  }) {
    final numSamples = (sampleRate * (duration.inMicroseconds / 1000000.0))
        .round();
    final pcmDataSize = numSamples * 2;
    final fileSize = 36 + pcmDataSize;

    final bytes = ByteData(44 + pcmDataSize);

    // RIFF header
    bytes.setUint8(0, 0x52); // R
    bytes.setUint8(1, 0x49); // I
    bytes.setUint8(2, 0x46); // F
    bytes.setUint8(3, 0x46); // F
    bytes.setUint32(4, fileSize, Endian.little);
    bytes.setUint8(8, 0x57); // W
    bytes.setUint8(9, 0x41); // A
    bytes.setUint8(10, 0x56); // V
    bytes.setUint8(11, 0x45); // E

    // fmt subchunk
    bytes.setUint8(12, 0x66); // f
    bytes.setUint8(13, 0x6d); // m
    bytes.setUint8(14, 0x74); // t
    bytes.setUint8(15, 0x20); // ' '
    bytes.setUint32(16, 16, Endian.little);
    bytes.setUint16(20, 1, Endian.little);
    bytes.setUint16(22, 1, Endian.little);
    bytes.setUint32(24, sampleRate, Endian.little);
    bytes.setUint32(28, sampleRate * 2, Endian.little);
    bytes.setUint16(32, 2, Endian.little);
    bytes.setUint16(34, 16, Endian.little);

    // data subchunk
    bytes.setUint8(36, 0x64); // d
    bytes.setUint8(37, 0x61); // a
    bytes.setUint8(38, 0x74); // t
    bytes.setUint8(39, 0x61); // a
    bytes.setUint32(40, pcmDataSize, Endian.little);

    final periodSamples = sampleRate / frequency;

    final attackSamples = (sampleRate * 0.005).round(); // 5ms attack
    final decaySamples = (sampleRate * 0.010).round(); // 10ms decay
    final attackStep = attackSamples > 0 ? math.pi / attackSamples : 0.0;
    final decayStep = decaySamples > 0 ? math.pi / decaySamples : 0.0;

    for (int i = 0; i < numSamples; i++) {
      final t = (i % periodSamples) / periodSamples;
      final sampleValue = switch (shape) {
        WaveForm.square => t < 0.5 ? 0.8 : -0.8,
        WaveForm.saw => 2.0 * t - 1.0,
        WaveForm.sin => math.sin(2.0 * math.pi * t),
        WaveForm.triangle || _ => t < 0.5 ? (4.0 * t - 1.0) : (3.0 - 4.0 * t),
      };

      double envelope = 1.0;
      if (i < attackSamples) {
        envelope = (1.0 - math.cos(i * attackStep)) / 2.0;
      } else if (i > numSamples - decaySamples) {
        final decayI = i - (numSamples - decaySamples);
        envelope = (1.0 + math.cos(decayI * decayStep)) / 2.0;
      }

      final int16Value = (sampleValue * envelope * 32767.0)
          .clamp(-32768.0, 32767.0)
          .round();
      bytes.setInt16(44 + i * 2, int16Value, Endian.little);
    }

    return bytes.buffer.asUint8List();
  }

  @override
  Future<AudioBuffer> loadMem(String pathId, Uint8List bytes) async {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final source = await _engine.loadMem(pathId, bytes);
    return FlutterAudioBuffer(source, this);
  }

  @override
  Future<AudioBuffer> loadWaveform(
    WaveForm shape,
    double frequency, {
    bool usePcmFallback = false,
  }) async {
    if (usePcmFallback) {
      final pcmBytes = _generateWaveformPcmWav(
        shape: shape,
        frequency: frequency,
      );
      final path = 'synthetic_${shape.name}_${frequency.toInt()}.wav';
      final source = await _engine.loadMem(path, pcmBytes);
      return FlutterAudioBuffer(source, this);
    } else {
      final solShape = sol.WaveForm.values.firstWhere(
        (e) => e.name == shape.name,
      );
      final source = await _engine.loadWaveform(solShape, true, 1.0, 0.0);
      _engine.setWaveformFreq(source, frequency);
      return FlutterAudioBuffer(source, this);
    }
  }

  @override
  AudioVoice play(
    AudioBuffer buffer, {
    bool loop = false,
    AudioBus? bus,
    bool paused = false,
  }) {
    if (buffer case FlutterAudioBuffer(:final source)) {
      final busId = bus?.id ?? 0;
      final voice = _engine.play(
        source,
        looping: loop,
        busId: busId,
        paused: paused,
      );
      final completer = Completer<void>();
      _activeVoices[voice.id] = completer;
      return AudioVoice(voice.id, completer.future);
    }
    throw ArgumentError('Expected FlutterAudioBuffer');
  }

  @override
  void stop(AudioVoice voice) {
    sol.SoLoud.instance.stop(sol.SoundHandle(voice.id));
    _completeVoice(voice.id);
  }

  @override
  void setPaused(AudioVoice voice, bool paused) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    sol.SoLoud.instance.setPause(sol.SoundHandle(voice.id), paused);
  }

  @override
  void setVoiceVolume(AudioVoice voice, double volume) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    sol.SoLoud.instance.setVolume(sol.SoundHandle(voice.id), volume);
  }

  @override
  AudioVoice play3d(AudioBuffer buffer, double x, double y, double z) {
    if (buffer case FlutterAudioBuffer(:final source)) {
      final voice = _engine.play3d(source, x, y, z);
      final completer = Completer<void>();
      _activeVoices[voice.id] = completer;
      return AudioVoice(voice.id, completer.future);
    }
    throw ArgumentError('Expected FlutterAudioBuffer');
  }

  @override
  void set3dSourceParameters(
    AudioVoice voice,
    double x,
    double y,
    double z, {
    double vx = 0.0,
    double vy = 0.0,
    double vz = 0.0,
  }) {
    _engine.set3dSourceParameters(
      sol.SoundHandle(voice.id),
      x,
      y,
      z,
      vx,
      vy,
      vz,
    );
  }

  @override
  void set3dSourceMinMaxDistance(
    AudioVoice voice,
    double minDistance,
    double maxDistance,
  ) {
    _engine.set3dSourceMinMaxDistance(
      sol.SoundHandle(voice.id),
      minDistance,
      maxDistance,
    );
  }

  @override
  void set3dSourceAttenuation(
    AudioVoice voice,
    AttenuationModel attenuationModel,
    double attenuationRolloffFactor,
  ) {
    _engine.set3dSourceAttenuation(
      sol.SoundHandle(voice.id),
      attenuationModel.index,
      attenuationRolloffFactor,
    );
  }

  @override
  void setRelativePlaySpeed(AudioVoice voice, double speed) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    _engine.setRelativePlaySpeed(sol.SoundHandle(voice.id), speed);
  }

  @override
  void fadeRelativePlaySpeed(
    AudioVoice voice,
    double speed,
    Duration duration,
  ) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    _engine.fadeRelativePlaySpeed(sol.SoundHandle(voice.id), speed, duration);
  }

  @override
  void fadeVolume(AudioVoice voice, double targetVolume, Duration duration) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    _engine.fadeVolume(sol.SoundHandle(voice.id), targetVolume, duration);
  }

  @override
  void scheduleStop(AudioVoice voice, Duration duration) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    _engine.scheduleStop(sol.SoundHandle(voice.id), duration);
  }

  @override
  int createFilter(FilterType type) {
    return type.index;
  }

  @override
  void attachFilterToBus(AudioBus bus, int filterId) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solFilter = sol.FilterType.values[filterId];
    // ignore: invalid_use_of_internal_member
    solFilter.activate(null, bus.id);
  }

  @override
  void setFilterParameter(
    AudioBus bus,
    int filterId,
    int paramId,
    double value,
  ) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solFilter = sol.FilterType.values[filterId];
    // ignore: invalid_use_of_internal_member
    soloud_controller.SoLoudController().soLoudFFI.setFilterParams(
      solFilter,
      paramId,
      value,
      handle: null,
      busId: bus.id,
    );
  }

  @override
  double getFilterParameter(AudioBus bus, int filterId, int paramId) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solFilter = sol.FilterType.values[filterId];
    // ignore: invalid_use_of_internal_member
    final result = soloud_controller.SoLoudController().soLoudFFI
        .getFilterParams(solFilter, paramId, busId: bus.id);
    return result.value;
  }

  @override
  void fadeFilterParameter(
    AudioBus bus,
    int filterId,
    int paramId,
    double targetValue,
    Duration duration,
  ) {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solFilter = sol.FilterType.values[filterId];
    if (duration == Duration.zero) {
      soloud_controller.SoLoudController().soLoudFFI.setFilterParams(
        solFilter,
        paramId,
        targetValue,
        handle: null,
        busId: bus.id,
      );
    } else {
      // ignore: invalid_use_of_internal_member
      solFilter.fadeFilterParameter(
        null,
        bus.id,
        paramId,
        targetValue,
        duration,
      );
    }
  }

  @override
  AudioVoice playSprite(
    AudioBuffer buffer, {
    AudioBus? bus,
    required Duration start,
    required Duration duration,
  }) {
    final voice = play(buffer, paused: true);
    if (start > Duration.zero) {
      seek(voice, start);
    }
    setPaused(voice, false);
    scheduleStop(voice, duration);
    return voice;
  }

  @override
  void playSpriteSequence(
    AudioBuffer buffer,
    List<SpriteSegment> segments, {
    AudioBus? bus,
  }) {
    if (!_engine.isInitialized || segments.isEmpty) return;

    var totalDelay = Duration.zero;
    for (final seg in segments) {
      final segDelay = totalDelay;
      totalDelay += seg.duration;

      void playSegment() {
        if (!_engine.isInitialized) return;
        final voice = play(buffer, bus: bus, paused: true);
        if (seg.start > Duration.zero) {
          seek(voice, seg.start);
        }

        setPaused(voice, false);
        // Eagerly schedule a stop exactly when the segment finishes on the C++ side
        scheduleStop(voice, seg.duration);
      }

      if (segDelay == Duration.zero) {
        playSegment();
      } else {
        unawaited(Future.delayed(segDelay, playSegment));
      }
    }
  }

  @override
  AudioBus createBus() {
    if (!_engine.isInitialized) throw Exception('Engine not initialized.');
    final solBus = sol.Bus();
    solBus.playOnEngine();
    return FlutterAudioBus(solBus);
  }

  @override
  void destroyBus(AudioBus bus) {
    if (!_engine.isInitialized) return;
    if (bus case FlutterAudioBus b) {
      b._bus.dispose();
    }
  }

  @override
  Float32List getWaveform([Float32List? outBuffer]) {
    if (outBuffer != null && outBuffer.length < 256) {
      throw ArgumentError('outBuffer must be at least 256 elements long.');
    }
    final buffer = outBuffer ?? Float32List(256);
    if (_audioData == null) return buffer;

    _audioData!.updateSamples();
    final data = _audioData!.getAudioData(alwaysReturnData: true);
    buffer.setAll(0, data);
    return buffer;
  }
}
