import 'dart:async';
import 'dart:ffi';
import 'dart:io';
import 'package:file/file.dart';
import 'package:file/local.dart';
import 'package:ffi/ffi.dart';
import '../../api/audio_engine.dart';
import '../../api/audio_types.dart';
import '../../soloud_cli.dart' as ffi;
import '../../soloud_cli.dart' show SoLoud_destroySound;

/// An audio buffer loaded into the CLI backend.
class CliAudioBuffer implements AudioBuffer, Finalizable {
  /// The unique hash identifier generated by the SoLoud backend.
  @override
  final int hash;

  /// Creates a new CLI audio buffer.
  const CliAudioBuffer(this.hash);
}

/// A mixing bus for grouping audio voices in the CLI backend.
class CliAudioBus implements AudioBus {
  /// The unique ID of the bus.
  @override
  final int id;

  /// Creates a new CLI audio bus.
  const CliAudioBus(this.id);

  /// Sets the volume for this bus.
  @override
  void setVolume(double volume) {
    ffi.setVolume(id, volume);
  }
}

/// The CLI implementation of [TermuiAudioEngine].
class CliAudioEngine implements TermuiAudioEngine {
  /// The file system to use for loading audio files.
  final FileSystem fileSystem;

  /// Creates a new CLI audio engine.
  CliAudioEngine({this.fileSystem = const LocalFileSystem()});
  bool _inited = false;
  StreamSubscription<ProcessSignal>? _sigintSub;

  final Map<int, List<int>> _playingVoices = {};

  // Auto-Reclaiming Memory (NativeFinalizer)
  late final NativeFinalizer _soundFinalizer = NativeFinalizer(
    Native.addressOf<NativeFunction<Void Function(Pointer<Void>)>>(
      SoLoud_destroySound,
    ),
  );

  @override
  Future<void> init() async {
    if (_inited) return;

    try {
      // ProcessSignal isn't easily mockable, but we only attach it safely
      _sigintSub = ProcessSignal.sigint.watch().listen((_) {
        ffi.disposeEngine();
        exit(0);
      });
    } catch (_) {}

    final res = ffi.initEngine(-1, 48000, 2048, 2, 0);
    if (res != 0) {
      throw Exception(
        'Failed to initialize SoLoud CLI Engine. Error code: $res',
      );
    }
    _inited = true;
  }

  @override
  Future<void> dispose() async {
    if (!_inited) return;

    await _sigintSub?.cancel();
    _sigintSub = null;

    ffi.disposeEngine();
    _playingVoices.clear();
    _inited = false;
  }

  @override
  Future<AudioBuffer> loadFile(
    String path, {
    LoadProgressCallback? onProgress,
  }) async {
    if (!_inited) throw Exception('Engine not initialized.');

    final file = fileSystem.file(path);
    if (!await file.exists()) {
      throw FileSystemException('Sound file not found', path);
    }

    final length = await file.length();
    if (length == 0) {
      throw FileSystemException('Sound file is empty', path);
    }

    final bufferPtr = calloc<Uint8>(length);
    int offset = 0;

    try {
      await for (final chunk in file.openRead()) {
        final chunkSize = chunk.length;
        if (offset + chunkSize > length) {
          break; // File grew while reading, ignore extra bytes to prevent overflow
        }
        bufferPtr.asTypedList(length).setAll(offset, chunk);
        offset += chunkSize;
        onProgress?.call(offset / length);
      }

      final namePtr = path.toNativeUtf8().cast<Char>();
      final hashPtr = calloc<Uint32>();

      try {
        final res = ffi.loadMem(namePtr, bufferPtr, offset, 1, hashPtr);
        if (res != 0) {
          throw Exception('Failed to load sound into memory. Error code: $res');
        }
        final hash = hashPtr.value;
        onProgress?.call(1.0);

        final buffer = CliAudioBuffer(hash);
        _soundFinalizer.attach(
          buffer,
          Pointer.fromAddress(hash),
          detach: buffer,
        );
        return buffer;
      } finally {
        calloc.free(namePtr);
        calloc.free(hashPtr);
      }
    } finally {
      calloc.free(bufferPtr);
    }
  }

  @override
  Future<AudioBuffer> loadUrl(
    String url, {
    LoadProgressCallback? onProgress,
  }) async {
    throw UnimplementedError(
      'please file a feature request at github.com/jtmcdole/termui for loadUrl in CLI',
    );
  }

  @override
  Future<AudioBuffer> loadWaveform(WaveForm shape, double frequency) async {
    throw UnimplementedError(
      'please file a feature request at github.com/jtmcdole/termui for loadWaveform in CLI',
    );
  }

  @override
  AudioVoice play(AudioBuffer buffer, {bool loop = false, AudioBus? bus}) {
    if (!_inited) throw Exception('Engine not initialized.');

    final hash = buffer.hash;
    final voicePtr = calloc<Uint32>();
    try {
      final busId = bus?.id ?? 0;
      final res = ffi.play(hash, busId, 1.0, 0.0, false, loop, 0.0, voicePtr);
      if (res != 0) {
        throw Exception('Failed to play sound. Error code: $res');
      }
      final voiceId = voicePtr.value;
      _playingVoices.putIfAbsent(hash, () => []).add(voiceId);
      return AudioVoice(voiceId);
    } finally {
      calloc.free(voicePtr);
    }
  }

  @override
  void stop(AudioVoice voice) {
    if (!_inited) return;
    ffi.stop(voice.id);
  }

  @override
  AudioVoice play3d(AudioBuffer buffer, double x, double y, double z) {
    if (!_inited) throw Exception('Engine not initialized.');

    final hash = buffer.hash;
    final voicePtr = calloc<Uint32>();
    try {
      final res = ffi.play3d(
        hash,
        0,
        x,
        y,
        z,
        0.0,
        0.0,
        0.0,
        1.0,
        false,
        false,
        0.0,
        voicePtr,
      );
      if (res != 0) {
        throw Exception('Failed to play 3D sound. Error code: $res');
      }
      final voiceId = voicePtr.value;
      _playingVoices.putIfAbsent(hash, () => []).add(voiceId);
      return AudioVoice(voiceId);
    } finally {
      calloc.free(voicePtr);
    }
  }

  @override
  void set3dSourceParameters(
    AudioVoice voice,
    double x,
    double y,
    double z, {
    double vx = 0.0,
    double vy = 0.0,
    double vz = 0.0,
  }) {
    if (!_inited) return;
    ffi.set3dSourceParameters(voice.id, x, y, z, vx, vy, vz);
  }
}
