import 'dart:async';
import 'dart:ffi';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';
import 'package:file/file.dart';
import 'package:file/local.dart';
import 'package:ffi/ffi.dart';
import '../../api/audio_engine.dart';
import '../../api/audio_types.dart';
import '../../soloud_cli.dart' as ffi;
import '../../soloud_cli.dart' show SoLoud_destroySound;

int _fileLoadCounter = 0;

/// An audio buffer loaded into the CLI backend.
class CliAudioBuffer implements AudioBuffer, Finalizable {
  /// The unique hash identifier generated by the SoLoud backend.
  @override
  final int hash;

  /// Creates a new CLI audio buffer.
  const CliAudioBuffer(this.hash);
}

/// A mixing bus for grouping audio voices in the CLI backend.
class CliAudioBus implements AudioBus {
  /// The unique ID of the bus.
  @override
  final int id;

  /// Creates a new CLI audio bus.
  const CliAudioBus(this.id);

  /// Sets the volume for this bus.
  @override
  void setVolume(double volume) {
    ffi.setVolume(id, volume);
  }
}

/// The CLI implementation of [TermuiAudioEngine].
class CliAudioEngine implements TermuiAudioEngine {
  /// The file system to use for loading audio files.
  final FileSystem fileSystem;

  /// Creates a new CLI audio engine.
  CliAudioEngine({this.fileSystem = const LocalFileSystem()});
  bool _inited = false;
  StreamSubscription<ProcessSignal>? _sigintSub;

  static final Map<int, Completer<void>> _activeVoices = {};

  static void _voiceEndedCallback(Pointer<Uint32> handlePtr) {
    final handle = handlePtr.value;
    final completer = _activeVoices.remove(handle);
    if (completer != null && !completer.isCompleted) {
      completer.complete();
    }
  }

  static void _fileLoadedCallback(
    Pointer<Int32> a,
    Pointer<Utf8> b,
    Pointer<Uint32> c,
    Pointer<Uint64> d,
  ) {}
  static void _stateChangedCallback(Pointer<Int32> a) {}

  late final NativeCallable<ffi.DartVoiceEndedFunction> _voiceEndedCallable;
  late final NativeCallable<ffi.DartFileLoadedFunction> _fileLoadedCallable;
  late final NativeCallable<ffi.DartStateChangedFunction> _stateChangedCallable;

  // Auto-Reclaiming Memory (NativeFinalizer)
  late final NativeFinalizer _soundFinalizer = NativeFinalizer(
    Native.addressOf<NativeFunction<Void Function(Pointer<Void>)>>(
      SoLoud_destroySound,
    ),
  );

  @override
  Future<void> init() async {
    if (_inited) return;

    try {
      // ProcessSignal isn't easily mockable, but we only attach it safely
      _sigintSub = ProcessSignal.sigint.watch().listen((_) {
        ffi.disposeEngine();
        exit(0);
      });
    } catch (_) {}

    final res = ffi.initEngine(-1, 48000, 2048, 2, 0);
    if (res != 0) {
      throw Exception(
        'Failed to initialize SoLoud CLI Engine. Error code: $res',
      );
    }

    _voiceEndedCallable = NativeCallable<ffi.DartVoiceEndedFunction>.listener(
      _voiceEndedCallback,
    );
    _fileLoadedCallable = NativeCallable<ffi.DartFileLoadedFunction>.listener(
      _fileLoadedCallback,
    );
    _stateChangedCallable =
        NativeCallable<ffi.DartStateChangedFunction>.listener(
          _stateChangedCallback,
        );

    ffi.setDartEventCallback(
      _voiceEndedCallable.nativeFunction.cast(),
      _fileLoadedCallable.nativeFunction.cast(),
      _stateChangedCallable.nativeFunction.cast(),
    );

    _inited = true;
  }

  @override
  Future<void> dispose() async {
    if (!_inited) return;

    await _sigintSub?.cancel();
    _sigintSub = null;

    ffi.disposeEngine();
    for (final c in _activeVoices.values) {
      if (!c.isCompleted) c.complete();
    }
    _activeVoices.clear();

    _voiceEndedCallable.close();
    _fileLoadedCallable.close();
    _stateChangedCallable.close();

    _inited = false;
  }

  @override
  Duration getBufferDuration(AudioBuffer buffer) {
    if (!_inited) return Duration.zero;
    final lengthSecs = ffi.getLength(buffer.hash);
    return Duration(microseconds: (lengthSecs * 1000000).round());
  }

  @override
  Duration getVoicePosition(AudioVoice voice) {
    if (!_inited) return Duration.zero;
    final posSecs = ffi.getPosition(voice.id);
    return Duration(microseconds: (posSecs * 1000000).round());
  }

  @override
  void seek(AudioVoice voice, Duration position) {
    if (!_inited) return;
    ffi.seek(voice.id, position.inMicroseconds / 1000000.0);
  }

  @override
  void setVoiceVolume(AudioVoice voice, double volume) {
    if (!_inited) throw Exception('Engine not initialized.');
    ffi.setVolume(voice.id, volume);
  }

  @override
  Future<AudioBuffer> loadFile(
    String path, {
    LoadProgressCallback? onProgress,
  }) async {
    if (!_inited) throw Exception('Engine not initialized.');

    final file = fileSystem.file(path);
    if (!await file.exists()) {
      throw FileSystemException('Sound file not found', path);
    }

    final bytes = await file.readAsBytes();
    final length = bytes.length;
    if (length == 0) {
      throw FileSystemException('Sound file is empty', path);
    }

    final bufferPtr = calloc<Uint8>(length);

    try {
      bufferPtr.asTypedList(length).setAll(0, bytes);
      onProgress?.call(1.0);

      final extIndex = path.lastIndexOf('.');
      final uniqueId = _fileLoadCounter++;
      final uniquePath = extIndex == -1
          ? '${path}_$uniqueId'
          : '${path.substring(0, extIndex)}_$uniqueId${path.substring(extIndex)}';

      final namePtr = uniquePath.toNativeUtf8().cast<Char>();
      final hashPtr = calloc<Uint32>();

      try {
        final res = ffi.loadMem(namePtr, bufferPtr, length, 1, hashPtr);
        if (res != 0) {
          throw Exception('Failed to load sound into memory. Error code: $res');
        }
        final hash = hashPtr.value;
        onProgress?.call(1.0);

        final buffer = CliAudioBuffer(hash);
        _soundFinalizer.attach(
          buffer,
          Pointer.fromAddress(hash),
          detach: buffer,
        );
        return buffer;
      } finally {
        calloc.free(namePtr);
        calloc.free(hashPtr);
      }
    } finally {
      calloc.free(bufferPtr);
    }
  }

  @override
  Future<AudioBuffer> loadUrl(
    String url, {
    LoadProgressCallback? onProgress,
  }) async {
    throw UnimplementedError(
      'please file a feature request at github.com/jtmcdole/termui for loadUrl in CLI',
    );
  }

  @override
  Future<AudioBuffer> loadWaveform(WaveForm shape, double frequency) async {
    if (!_inited) throw Exception('Engine not initialized.');

    final wavBytes = _generateWavBytes(shape, frequency);
    final length = wavBytes.length;
    final bufferPtr = calloc<Uint8>(length);

    try {
      bufferPtr.asTypedList(length).setAll(0, wavBytes);

      final uniqueId = _fileLoadCounter++;
      final uniquePath =
          'waveform_${shape.name}_${frequency.toInt()}_$uniqueId.wav';

      final namePtr = uniquePath.toNativeUtf8().cast<Char>();
      final hashPtr = calloc<Uint32>();

      try {
        final res = ffi.loadMem(namePtr, bufferPtr, length, 1, hashPtr);
        if (res != 0) {
          throw Exception(
            'Failed to load synthetic waveform into memory. Error code: $res',
          );
        }
        final hash = hashPtr.value;

        final buffer = CliAudioBuffer(hash);
        _soundFinalizer.attach(
          buffer,
          Pointer.fromAddress(hash),
          detach: buffer,
        );
        return buffer;
      } finally {
        calloc.free(namePtr);
        calloc.free(hashPtr);
      }
    } finally {
      calloc.free(bufferPtr);
    }
  }

  Uint8List _generateWavBytes(
    WaveForm shape,
    double frequency, {
    double durationSeconds = 0.25,
    int sampleRate = 44100,
  }) {
    final numSamples = (sampleRate * durationSeconds).round();
    final pcmByteLength = numSamples * 2;
    final totalLength = 44 + pcmByteLength;
    final bytes = Uint8List(totalLength);
    final bd = ByteData.sublistView(bytes);

    bytes.setRange(0, 4, 'RIFF'.codeUnits);
    bd.setUint32(4, totalLength - 8, Endian.little);
    bytes.setRange(8, 12, 'WAVE'.codeUnits);
    bytes.setRange(12, 16, 'fmt '.codeUnits);
    bd.setUint32(16, 16, Endian.little);
    bd.setUint16(20, 1, Endian.little);
    bd.setUint16(22, 1, Endian.little);
    bd.setUint32(24, sampleRate, Endian.little);
    bd.setUint32(28, sampleRate * 2, Endian.little);
    bd.setUint16(32, 2, Endian.little);
    bd.setUint16(34, 16, Endian.little);
    bytes.setRange(36, 40, 'data'.codeUnits);
    bd.setUint32(40, pcmByteLength, Endian.little);

    final attackSamples = (sampleRate * 0.005)
        .round(); // 5ms smooth attack fade-in
    final decaySamples = (sampleRate * 0.010)
        .round(); // 10ms smooth decay fade-out
    final attackStep = attackSamples > 0 ? math.pi / attackSamples : 0.0;
    final decayStep = decaySamples > 0 ? math.pi / decaySamples : 0.0;

    for (int i = 0; i < numSamples; i++) {
      final t = i / sampleRate;
      final phase = (t * frequency) % 1.0;
      double sample;
      switch (shape) {
        case WaveForm.sin:
          sample = math.sin(2.0 * math.pi * phase);
        case WaveForm.triangle:
          sample = phase < 0.5 ? (4.0 * phase - 1.0) : (3.0 - 4.0 * phase);
        case WaveForm.saw || WaveForm.fsaw:
          sample = 2.0 * phase - 1.0;
        case WaveForm.bounce || WaveForm.jaws || WaveForm.humps:
          sample = (math.sin(2.0 * math.pi * phase)).abs() * 2.0 - 1.0;
        case WaveForm.square || WaveForm.fsquare:
          sample = phase < 0.5 ? 0.7 : -0.7;
      }

      // Smooth cosine windowing at boundaries to prevent DC offset clicks/pops
      if (i < attackSamples) {
        final gain = 0.5 * (1.0 - math.cos(i * attackStep));
        sample *= gain;
      } else if (i >= numSamples - decaySamples) {
        final rem = numSamples - 1 - i;
        final gain = 0.5 * (1.0 - math.cos(rem * decayStep));
        sample *= gain;
      }

      final intSample = (sample * 32767.0).clamp(-32768.0, 32767.0).toInt();
      bd.setInt16(44 + i * 2, intSample, Endian.little);
    }
    return bytes;
  }

  @override
  AudioVoice play(AudioBuffer buffer, {bool loop = false, AudioBus? bus}) {
    if (!_inited) throw Exception('Engine not initialized.');

    final hash = buffer.hash;
    final voicePtr = calloc<Uint32>();
    try {
      final busId = bus?.id ?? 0;
      final res = ffi.play(hash, busId, 1.0, 0.0, false, loop, 0.0, voicePtr);
      if (res != 0) {
        throw Exception('Failed to play sound. Error code: $res');
      }
      final voiceId = voicePtr.value;
      final completer = Completer<void>();
      _activeVoices[voiceId] = completer;
      return AudioVoice(voiceId, completer.future);
    } finally {
      calloc.free(voicePtr);
    }
  }

  @override
  void stop(AudioVoice voice) {
    if (!_inited) return;
    ffi.stop(voice.id);
  }

  @override
  AudioVoice play3d(AudioBuffer buffer, double x, double y, double z) {
    if (!_inited) throw Exception('Engine not initialized.');

    final hash = buffer.hash;
    final voicePtr = calloc<Uint32>();
    try {
      final res = ffi.play3d(
        hash,
        0,
        x,
        y,
        z,
        0.0,
        0.0,
        0.0,
        1.0,
        false,
        false,
        0.0,
        voicePtr,
      );
      if (res != 0) {
        throw Exception('Failed to play 3D sound. Error code: $res');
      }
      final voiceId = voicePtr.value;
      final completer = Completer<void>();
      _activeVoices[voiceId] = completer;
      return AudioVoice(voiceId, completer.future);
    } finally {
      calloc.free(voicePtr);
    }
  }

  @override
  void set3dSourceParameters(
    AudioVoice voice,
    double x,
    double y,
    double z, {
    double vx = 0.0,
    double vy = 0.0,
    double vz = 0.0,
  }) {
    if (!_inited) return;
    ffi.set3dSourceParameters(voice.id, x, y, z, vx, vy, vz);
  }

  @override
  void set3dSourceMinMaxDistance(
    AudioVoice voice,
    double minDistance,
    double maxDistance,
  ) {
    if (!_inited) return;
    ffi.set3dSourceMinMaxDistance(voice.id, minDistance, maxDistance);
  }

  @override
  void set3dSourceAttenuation(
    AudioVoice voice,
    AttenuationModel attenuationModel,
    double attenuationRolloffFactor,
  ) {
    if (!_inited) return;
    ffi.set3dSourceAttenuation(
      voice.id,
      attenuationModel.index,
      attenuationRolloffFactor,
    );
  }

  @override
  void setRelativePlaySpeed(AudioVoice voice, double speed) {
    if (!_inited) throw Exception('Engine not initialized.');
    ffi.setRelativePlaySpeed(voice.id, speed);
  }

  @override
  void fadeRelativePlaySpeed(
    AudioVoice voice,
    double speed,
    Duration duration,
  ) {
    if (!_inited) throw Exception('Engine not initialized.');
    ffi.fadeRelativePlaySpeed(
      voice.id,
      speed,
      duration.inMicroseconds / 1000000.0,
    );
  }

  @override
  void fadeVolume(AudioVoice voice, double targetVolume, Duration duration) {
    if (!_inited) throw Exception('Engine not initialized.');
    ffi.fadeVolume(voice.id, targetVolume, duration.inMicroseconds / 1000000.0);
  }

  @override
  int createFilter(FilterType type) {
    return type.index;
  }

  @override
  void attachFilterToBus(AudioBus bus, int filterId) {
    if (!_inited) throw Exception('Engine not initialized.');
    final res = ffi.addFilter(0, bus.id, filterId);
    if (res != 0) {
      throw Exception('Failed to attach filter to bus. Error code: $res');
    }
  }

  @override
  void setFilterParameter(
    AudioBus bus,
    int filterId,
    int paramId,
    double value,
  ) {
    if (!_inited) throw Exception('Engine not initialized.');
    ffi.setFilterParams(0, bus.id, filterId, paramId, value);
  }

  @override
  void fadeFilterParameter(
    AudioBus bus,
    int filterId,
    int paramId,
    double targetValue,
    Duration duration,
  ) {
    if (!_inited) throw Exception('Engine not initialized.');
    ffi.fadeFilterParameter(
      0,
      bus.id,
      filterId,
      paramId,
      targetValue,
      duration.inMicroseconds / 1000000.0,
    );
  }

  @override
  AudioVoice playSprite(
    AudioBuffer buffer, {
    required Duration start,
    required Duration duration,
  }) {
    if (!_inited) throw Exception('Engine not initialized.');
    final voice = play(buffer);
    seek(voice, start);
    Timer(duration, () {
      try {
        stop(voice);
      } catch (_) {}
    });
    return voice;
  }

  @override
  void playSpriteSequence(
    AudioBuffer buffer,
    List<SpriteSegment> segments, {
    AudioBus? bus,
  }) {
    if (!_inited || segments.isEmpty) return;

    var totalDelay = Duration.zero;
    for (final seg in segments) {
      final segDelay = totalDelay;
      totalDelay += seg.duration;

      if (segDelay == Duration.zero) {
        final voicePtr = calloc<Uint32>();
        try {
          final startSec = seg.start.inMicroseconds / 1000000.0;
          final busId = bus?.id ?? 0;
          final res = ffi.play(
            buffer.hash,
            busId,
            1.0,
            0.0,
            false,
            false,
            startSec,
            voicePtr,
          );
          if (res == 0) {
            final voice = voicePtr.value;
            final durationSec = seg.duration.inMicroseconds / 1000000.0;
            ffi.fadeVolume(voice, 0.0, durationSec);
          }
        } finally {
          calloc.free(voicePtr);
        }
      } else {
        unawaited(
          Future.delayed(segDelay, () {
            if (!_inited) return;
            final voicePtr = calloc<Uint32>();
            try {
              final startSec = seg.start.inMicroseconds / 1000000.0;
              final busId = bus?.id ?? 0;
              final res = ffi.play(
                buffer.hash,
                busId,
                1.0,
                0.0,
                false,
                false,
                startSec,
                voicePtr,
              );
              if (res == 0) {
                final voice = voicePtr.value;
                final durationSec = seg.duration.inMicroseconds / 1000000.0;
                ffi.fadeVolume(voice, 0.0, durationSec);
              }
            } finally {
              calloc.free(voicePtr);
            }
          }),
        );
      }
    }
  }

  @override
  AudioBus createBus() {
    if (!_inited) throw Exception('Engine not initialized.');
    final busId = ffi.createBus();
    if (busId == 0) {
      throw Exception('Failed to create native audio bus.');
    }
    ffi.busPlayOnEngine(busId, 1.0, false);
    return CliAudioBus(busId);
  }

  @override
  void destroyBus(AudioBus bus) {
    if (!_inited) throw Exception('Engine not initialized.');
    ffi.destroyBus(bus.id);
  }
}
