name: termui_shared_examples
description: Shared example widgets and screens for termui and termui_flutter.
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  termui:
    path: ../termui
  termui_recorder:
    path: ../termui_recorder
  characters: ^1.4.0
  file: ^7.0.1
