name: termui_shared_examples
description: Shared example widgets and screens for termui and termui_flutter.
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  termui: ^0.8.0
  termui_recorder: ^0.6.0+15
  termui_pty: ^0.3.12
  pty2: ^0.5.3
  characters: ^1.4.0
  file: ^7.0.1
  core_bus: ^1.0.1
